import type { NextPage } from 'next';
import Head from 'next/head';
import { NavBar } from '../components/navbar';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>dieco.dev - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
    
      <main className='px-4 py-9 min-h-screen col-start-2 overflow-x-hidden relative pb-24'>
        <h2 className='text-4xl font-bold mb-2'>Contact.</h2>
        <p className='text-md mb-12'>Get in touch or shoot me an email directly on <a href="mailto:diegoddiaz05@gmail.com" className='font-bold'>diegoddiaz05@gmail.com</a></p>

        {/* form */}
        <form className='flex flex-col gap-4'>
          <input className='border-[1px] rounded-md py-2 px-4 font-normal outline-none text-base' type="text" name="name" required placeholder='Name' aria-required />
          <input className='border-[1px] rounded-md py-2 px-4 font-normal outline-none text-base' type="email" name="email" required placeholder='Email' aria-required />
          <textarea className='border-[1px] rounded-md py-2 px-4 font-normal outline-none text-base resize-none' name="message" required rows={5} placeholder='Message' aria-required />
          <input className='flex place-items-center min-w-[150px] bg-yllw text-black font-semibold max-w-fit rounded-md px-8 py-2' type="submit" value="Send Message" />
        </form>
      </main>
    </>
  );
};

export default Home;