import type { NextPage } from 'next';
import Head from 'next/head';
import { Profile } from '../components/home/profile';
import { Tech } from '../components/home/tech';
import { NavBar } from '../components/navbar';
import { useInView } from 'react-intersection-observer';

const Home: NextPage = () => {
  const {ref, inView} = useInView();
  
  return (
    <>
      <Head>
        <title>dieco.dev - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar isVisible={!inView} />
    
      <main className='px-4 py-9 min-h-screen col-start-2 overflow-x-hidden relative pb-24'>
        <Profile reference={ref} />
        <Tech />
        <p className='dark:text-gray-400'>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate, vel sint quidem eius eum, eaque ratione blanditiis beatae eveniet aliquid voluptas dolorem nulla. Quis officiis et, blanditiis ullam possimus sed iusto similique! Labore laudantium repellat, illum libero quod molestiae repellendus nulla accusantium recusandae voluptatem! Ipsum obcaecati cumque in consequatur inventore exercitationem molestiae qui est. Voluptas possimus vitae officiis asperiores in? Impedit eaque, delectus obcaecati velit, fugit exercitationem vitae quo mollitia veritatis nisi magnam corporis veniam laboriosam consequuntur repellat quasi sit voluptates incidunt repellendus iste dolor. At tempora fugiat ipsam itaque temporibus ipsum modi corporis recusandae dicta minima? Alias ullam aliquam cumque natus repellendus, ipsam explicabo iste error iure quibusdam vitae praesentium dolore incidunt eligendi magnam dolor at odit est dicta ipsum earum. Fuga aperiam ab, deserunt aut quae, maiores labore aspernatur minus tenetur quos error, 
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate, vel sint quidem eius eum, eaque ratione blanditiis beatae eveniet aliquid voluptas dolorem nulla. Quis officiis et, blanditiis ullam possimus sed iusto similique! Labore laudantium repellat, illum libero quod molestiae repellendus nulla accusantium recusandae voluptatem! Ipsum obcaecati cumque in consequatur inventore exercitationem molestiae qui est. Voluptas possimus vitae officiis asperiores in? Impedit eaque, delectus obcaecati velit, fugit exercitationem vitae quo mollitia veritatis nisi magnam corporis veniam laboriosam consequuntur repellat quasi sit voluptates incidunt repellendus iste dolor. At tempora fugiat ipsam itaque temporibus ipsum modi corporis recusandae dicta minima? Alias ullam aliquam cumque natus repellendus, ipsam explicabo iste error iure quibusdam vitae praesentium dolore incidunt eligendi magnam dolor at odit est dicta ipsum earum. Fuga aperiam ab, deserunt aut quae, maiores labore aspernatur minus tenetur quos error, 
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate, vel sint quidem eius eum, eaque ratione blanditiis beatae eveniet aliquid voluptas dolorem nulla. Quis officiis et, blanditiis ullam possimus sed iusto similique! Labore laudantium repellat, illum libero quod molestiae repellendus nulla accusantium recusandae voluptatem! Ipsum obcaecati cumque in consequatur inventore exercitationem molestiae qui est. Voluptas possimus vitae officiis asperiores in? Impedit eaque, delectus obcaecati velit, fugit exercitationem vitae quo mollitia veritatis nisi magnam corporis veniam laboriosam consequuntur repellat quasi sit voluptates incidunt repellendus iste dolor. At tempora fugiat ipsam itaque temporibus ipsum modi corporis recusandae dicta minima? Alias ullam aliquam cumque natus repellendus, ipsam explicabo iste error iure quibusdam vitae praesentium dolore incidunt eligendi magnam dolor at odit est dicta ipsum earum. Fuga aperiam ab, deserunt aut quae, maiores labore aspernatur minus tenetur quos error, 
        </p>
      </main>
    </>
  );
};

export default Home;
